/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fxpsam_nativeJni_RfidNative */

#ifndef _Included_com_fxpsam_nativeJni_RfidNative
#define _Included_com_fxpsam_nativeJni_RfidNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    rfidOpen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_rfidOpen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    rfidClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_rfidClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    rfidPowerOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_rfidPowerOn
  (JNIEnv *env, jobject thiz);
  
/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    rfidPowerOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_rfidPowerOff
  (JNIEnv *env, jobject thiz);  


/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    psamReset
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_psamReset
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    psamClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_psamClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    psamApdu
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_psamApdu
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    readReg
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_readReg
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    writeReg
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_writeReg
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);
  
  
/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_get_ver
 * Signature: ([B)
 */
JNIEXPORT void JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiGetVer
  (JNIEnv *env, jobject thiz, jbyteArray result);  

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_psam_init
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiPsamInit
  (JNIEnv *env, jobject thiz, jint psam_slot, jbyteArray result);  

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_get_card_info
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiGetCardInfo
  (JNIEnv *env, jobject thiz, jbyteArray result);
   
/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_debit
 * Signature: ([B[B)I
 */ 
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiDebit
  (JNIEnv *env, jobject thiz, jbyteArray value, jbyteArray result);
   
/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_cpu_get_transaction_prove
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiCpuGetTransactionProve
  (JNIEnv *env, jobject thiz, jbyteArray value, jbyteArray result);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_m1_calc_tac
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiM1CalcTac
  (JNIEnv *env, jobject thiz, jbyteArray value, jbyteArray result);

/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_get_debug_step
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiGetDebugStep
  (JNIEnv *env, jobject thiz);


/*
 * Class:     com_fxpsam_nativeJni_RfidNative
 * Method:    sptc_reader_api_get_last_record
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_fxpsam_nativeJni_RfidNative_SptcReaderApiGetLastRecord
  (JNIEnv *env, jobject thiz, jbyteArray result);


#ifdef __cplusplus
}
#endif
#endif
